//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr4
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKER
    {
        public int ID { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public string PATRONYMIC { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
    }
}
